---
output:
  pdf_document: default
  word_document: default
urlcolor: blue
header-includes:
- \usepackage{lastpage}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhead[CO, CE]{TONGFEI ZHOU, 1004738448}
- \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
---



```{r setup, message = FALSE, echo=FALSE, include=FALSE}
# Students: You probably shouldn't change any of the code in this chunk.

# These are the packages you will need for this activity
packages_needed <- c("tidyverse", "googledrive", "readxl", "janitor", 
                     "lubridate", "opendatatoronto", "ggthemes")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
    }
  }
)

# Credit: package.check based on a helpful post from Vikram Baliga https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/

# Load tidyverse
library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = FALSE)
```





```{r load_data, echo=FALSE}
######################################################
# Step three: Load the COVID data from Toronto City. #
######################################################

# Saving the name of the file as an object and then using the object name in the
# following code is a helpful practice. Why? If we change the name of the file 
# being used, we'll only have to change it in one place. This helps us avoid 
# 'human error'.

daily_data <- "CityofToronto_COVID-19_Daily_Public_Reporting.xlsx"

# Cases reported by date (double check the sheet is correct)
# Should be a sheet names something like  
## 'Cases by Reported Date'
reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()

# Cases by outbreak type (double check the sheet is correct)
# Should be a sheet names something like  
## 'Cases by Outbreak Type and Epis'
outbreak_raw <- read_excel(daily_data, sheet = 4) %>% 
  clean_names()

# When was this data updated?
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "CityofToronto_COVID-19_NeighbourhoodData.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

#don't need these anymore
rm(daily_data, neighbourood_data)

#############################################################
# Step four: Load the neighbourhood data from Toronto City. #
#############################################################

# Get neighbourhood profile data
nbhood_profile <- readRDS("neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Makes sure shape info is in the most up to date format

```

Code last run `r Sys.Date()`.  
Daily: `r date_daily[1,1]`.   
Neighbourhood: `r date_nbhood[1,1]`. 

# Task 1: Daily cases
## Data wrangling

```{r cases_dw, echo=TRUE}
reported = reported_raw %>% 
  mutate_if(is.numeric, replace_na, replace = 0) %>%
  mutate(reported_date = date(reported_date)) %>%
  pivot_longer(-c(reported_date), names_to = "Status", values_to = "Cases") %>%
  mutate(Status = str_to_sentence(Status)) %>%
  mutate(Status = factor(Status, levels = c("Active", "Recovered", "Deceased")))
```


\newpage
## Data visualization

```{r cases_vis, echo=TRUE}
reported %>%
  ggplot(aes(x = reported_date, y = Cases, fill = Status)) + 
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Cases reported by day in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x = "Date",
       y = "Case count",
       caption = str_c("Created by: TONGFEI ZHOU for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n",
                       date_daily[1,1]
                       )) +
  scale_x_date(labels = scales::date_format("%d %b %y"), limits = c(date("2020-01-01"), Sys.Date())) +
  theme(legend.title = element_blank(), legend.position = c(.15, .8)) +
  scale_fill_manual(values = c("#003F5C", "#86BCB6", "#B9CA5D"), breaks = c("Active", "Recovered", "Deceased"))
```

\newpage
# Task 2: Outbreak type
## Data wrangling


```{r outbreak_dw, echo=TRUE}
outbreak = outbreak_raw %>%
  mutate(episode_week = date(episode_week)) %>%
  mutate(outbreak_or_sporadic = str_replace_all(outbreak_or_sporadic, "OB Associated", "Outbreak associated")) %>%
  mutate(outbreak_or_sporadic = factor(outbreak_or_sporadic, levels = c("Sporadic", "Outbreak associated")))

total = group_by(outbreak, episode_week)
total = summarise(total, total_cases = sum(cases), .groups = "drop")
outbreak = left_join(outbreak, total, by = "episode_week")
```

\newpage
## Data visualization

```{r outbreak_vis, echo=TRUE}
outbreak %>%
  ggplot(aes(x = episode_week, y = cases, fill = outbreak_or_sporadic)) + 
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Cases by outbreak type and week in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x = "Date",
       y = "Case count",
       caption = str_c("Created by: TONGFEI ZHOU for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n",
                       date_daily[1,1])) +
  scale_x_date(labels = scales::date_format("%d %b %y"), limits = c(date("2020-01-01"), Sys.Date()+7)) +
  scale_y_continuous(limits = c(0, max(outbreak$total_cases))) +
  theme(legend.title = element_blank(), legend.position = c(.15, .8)) +
  scale_fill_manual(values = c("#86BCB6", "#B9CA5D"), breaks = c("Sporadic", "Outbreak associated"))
```

\newpage
# Task 3: Neighbourhoods
## Data wrangling: part 1

```{r nbhood_dw_1, echo=TRUE}
income = nbhood_profile %>% 
  filter(Category == "Income" & Topic == "Low income in 2015")
income = income %>%
  filter(`_id` == 1143) # As required we use the id 1143th row
income = income %>% 
  pivot_longer(-c(`_id`, Category, Topic, `Data Source`, Characteristic, `City of Toronto`), names_to = "neighbourhood_name", values_to = "percentages") %>%
  mutate(percentages = parse_number(percentages)) %>%
  mutate(Characteristic = str_remove(Characteristic, "\\s"))
```

## Data wrangling: part 2

```{r nbhood_dw_2, echo=TRUE}
nbhoods_all = nbhoods_shape_raw %>%
  mutate(neighbourhood_name = str_remove(AREA_NAME, "\\s\\(\\d+\\)$")) %>%
  mutate(neighbourhood_name = case_when(
    neighbourhood_name == "North St.James Town" ~ "North St. James Town",
    neighbourhood_name == "Weston-Pellam Park" ~ "Weston-Pelham Park",
    neighbourhood_name == "Cabbagetown-South St.James Town" ~ "Cabbagetown-South St. James Town",
    TRUE ~ neighbourhood_name
  ))

nbhoods_all = left_join(nbhoods_all, income, by = "neighbourhood_name")
nbhoods_all = left_join(nbhoods_all, nbhood_raw, by = "neighbourhood_name")
nbhoods_all = nbhoods_all %>%
  rename(rate_per_100000 = rate_per_100_000_people)
```

## Data wrangling: part 3

```{r nbhood_dw_3, echo=TRUE}
med_inc = median(nbhoods_all$percentages, na.rm = TRUE)
med_rate = median(nbhoods_all$rate_per_100000, na.rm = TRUE)
nbhoods_final = nbhoods_all %>%
  mutate(nbhood_type = case_when(
    (percentages >= med_inc & rate_per_100000 >= med_rate) ~ "Higher low income rate, higher case rate",
    (percentages >= med_inc & rate_per_100000 < med_rate) ~ "Higher low income rate, lower case rate",
    (percentages < med_inc & rate_per_100000 >= med_rate) ~ "Lower low income rate, higher case rate",
    (percentages < med_inc & rate_per_100000 < med_rate) ~ "Lower low income rate, lower case rate"
  ))
```

\newpage
## Data visualization

```{r neighbourhood_graphs_1, fig.height=4, echo=TRUE}
ggplot(data = nbhoods_final) + 
  geom_sf(aes(fill = percentages)) + 
  theme_map() + 
  scale_fill_gradient(name="% low income", low = "darkgreen", high = "lightgrey") +
  labs(title = "Percentage of 18 to 64 year olds living in a low income family (2015)",
       subtitle = "Neighbourhoods of Toronto, Canada",
       caption = str_c("Created by: TONGFEI ZHOU for STA303/1002, U of T\n",
                       "Source: Census Profile 98-316-X2016001 via OpenData Toronto\n",
                       date_daily[1,1])) + 
  theme(legend.position = "right")
```

\newpage

```{r neighbourhood_graphs_2, fig.height=4, echo=TRUE}
ggplot(data = nbhoods_final) + 
  geom_sf(aes(fill = rate_per_100000)) + 
  theme_map() + 
  scale_fill_gradient(name="Cases per 100,000 people", low = "white", high = "darkorange") +
  labs(title = "COVID−19 cases per 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: TONGFEI ZHOU for STA303/1002, U of T\n",
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n",
                       date_daily[1,1])) + 
  theme(legend.position = "right")
```

\newpage

```{r neighbourhood_graphs_3, fig.height=4, echo=TRUE}
ggplot(data = nbhoods_final) + 
  geom_sf(aes(fill = nbhood_type)) + 
  theme_map() + 
  scale_fill_brewer(palette = "Set1", name="% of 18 to 64 year-olds in \n low income families and \n COVID-19 case rates") +
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: TONGFEI ZHOU for STA303/1002, U of T\n",
                       "Income data source: Census Profile 98-316-X2016001 via OpenData Toronto\n",
                       "COVID data source: Ontario Ministry of Health, Integrated Public\n",
                       "Health Information System and CORES\n",
                       date_daily[1,1])) + 
  theme(legend.position = "right")
```